version: '3.8'
services:
    redis:
        image: redis:alpine
        ports:
            - 6379:6379
        volumes:
            - ./config/redis.conf:/redis.conf
        command: [ "redis-server", "/redis.conf" ]
        container_name: redis-latam